# Generated by Django 2.0.6 on 2018-07-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('videoId', models.CharField(max_length=100, unique=True)),
                ('vote', models.IntegerField(default=0)),
            ],
        ),
    ]
