# Generated by Django 2.0.6 on 2018-07-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeJukebox', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('videoId', models.CharField(max_length=100)),
            ],
        ),
    ]
