# Generated by Django 2.0.6 on 2018-07-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeJukebox', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='videoId',
        ),
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtubeJukebox.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='youtubeJukebox.Video'),
            preserve_default=False,
        ),
    ]
