# Generated by Django 2.0.6 on 2018-07-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeJukebox', '0004_auto_20180703_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
